# Fiches enseignant des 30 projets : idée, fonctionnement, composants, difficulté (1 à 3)
FICHES = [
("Montrer en permanence le niveau d'eau d'un réservoir et prévenir quand il est plein ou vide.",
 "Des électrodes (ou un capteur de niveau) placées à plusieurs hauteurs sont lues par l'Arduino. Chaque niveau atteint allume une LED (25, 50, 75, 100 %) ; un buzzer sonne au niveau maximal ou minimal.",
 "Arduino Uno, capteur de niveau d'eau (ou fils/électrodes), 4 LED + résistances 220 Ω, buzzer.", 1),
("Ouvrir une porte uniquement avec un badge autorisé.",
 "Le module RC522 lit l'identifiant (UID) du badge par liaison SPI. Si l'UID est dans la liste autorisée, l'Arduino active un relais qui alimente la serrure quelques secondes ; sinon LED rouge et bip.",
 "Arduino Uno, module RFID RC522 + badges, module relais 5 V, serrure électrique 12 V, alimentation 12 V, LED verte/rouge, buzzer.", 2),
("Ouvrir une porte en tapant un code secret.",
 "Le clavier matriciel 4×4 est lu ligne par ligne. Le code saisi est comparé au code enregistré : s'il est juste, le relais ouvre la serrure ; après plusieurs erreurs, une alarme sonne.",
 "Arduino Uno, clavier 4×4, module relais, serrure électrique 12 V, alimentation 12 V, écran LCD I2C (facultatif), buzzer.", 2),
("Ouvrir une porte avec son empreinte digitale.",
 "Le capteur (R307 ou AS608) enregistre d'abord les empreintes, puis compare l'empreinte présentée. Il répond à l'Arduino par liaison série ; si l'empreinte est reconnue, le relais ouvre la serrure.",
 "Arduino Uno, capteur d'empreintes R307/AS608, module relais, serrure électrique 12 V, alimentation 12 V, LED.", 3),
("Lever automatiquement une barrière quand une voiture arrive.",
 "Le capteur HC-SR04 mesure la distance. Si un véhicule est à moins de quelques centimètres, le servomoteur lève la barrière, puis la baisse après son passage. Des LED indiquent passage libre ou interdit.",
 "Arduino Uno, capteur à ultrasons HC-SR04, servomoteur SG90, LED rouge et verte, maquette.", 1),
("Afficher l'heure et la date exactes, même après une coupure de courant.",
 "Le module RTC DS3231 compte le temps grâce à sa pile et communique en I2C. L'Arduino lit l'heure et l'affiche sur le LCD. Option : régler une alarme avec des boutons et un buzzer.",
 "Arduino Uno, module RTC DS3231 (ou DS1307), écran LCD 16×2 I2C, boutons, buzzer (option).", 1),
("Mesurer et afficher la température et l'humidité de l'air.",
 "Le capteur DHT11 envoie la température et l'humidité sur une seule broche numérique. L'Arduino les affiche sur le LCD et peut signaler un dépassement de seuil.",
 "Arduino Uno, capteur DHT11 (ou DHT22), écran LCD 16×2 I2C.", 1),
("Rentrer automatiquement le linge quand il commence à pleuvoir.",
 "Le capteur de pluie détecte les gouttes sur sa plaque. L'Arduino commande alors un moteur (ou servomoteur) qui tire le fil à linge sous un abri, puis le ressort quand il fait sec.",
 "Arduino Uno, module capteur de pluie, servomoteur ou moteur DC + module L298N, maquette (maison, fil à linge).", 2),
("Allumer une lampe pendant une durée choisie par l'utilisateur.",
 "La durée est réglée avec des boutons et affichée sur le LCD. Au démarrage, le relais allume la lampe ; l'Arduino compte le temps avec millis() et éteint la lampe à la fin.",
 "Arduino Uno, écran LCD 16×2 I2C, 3 boutons-poussoirs, module relais, lampe (de préférence 12 V pour la sécurité).", 2),
("Détecter une fuite de gaz et évacuer l'air.",
 "Le capteur MQ-2 donne une tension qui augmente avec la concentration de gaz ou de fumée. Au-delà d'un seuil, l'Arduino déclenche le buzzer et le relais met en marche le ventilateur.",
 "Arduino Uno, capteur de gaz MQ-2, module relais, ventilateur DC, buzzer, LED, LCD (option). Le MQ-2 doit chauffer quelques minutes avant des mesures fiables.", 1),
("Trier automatiquement les déchets humides et les déchets secs.",
 "Un capteur (IR ou ultrasons) détecte l'arrivée d'un déchet sur la trappe ; une sonde d'humidité teste s'il est mouillé. Le servomoteur incline la trappe vers le bac « humide » ou le bac « sec ».",
 "Arduino Uno, capteur IR ou HC-SR04, sonde d'humidité, servomoteur SG90, maquette avec deux bacs.", 2),
("Compter l'argent déposé dans une tirelire.",
 "Chaque pièce qui tombe coupe le faisceau d'un capteur infrarouge. L'Arduino compte les passages et affiche le total sur le LCD. Plusieurs capteurs, selon la taille des pièces, permettent de distinguer les valeurs.",
 "Arduino Uno, capteur(s) infrarouge(s), écran LCD 16×2 I2C, maquette de tirelire.", 2),
("Allumer automatiquement une lampe quand la lumière du jour diminue (exemple fil rouge du cours).",
 "La photorésistance forme un pont diviseur avec une résistance ; la tension sur A0 baisse quand il fait sombre. Sous un seuil, l'Arduino allume la LED ou active le relais de la lampe.",
 "Arduino Uno, photorésistance (LDR), résistance 10 kΩ, LED + 220 Ω ou module relais + lampe.", 1),
("Compter les personnes qui entrent et sortent d'une salle.",
 "Deux capteurs IR sont placés l'un après l'autre dans le passage. L'ordre dans lequel ils sont coupés indique une entrée ou une sortie ; le nombre de personnes présentes s'affiche sur le LCD. Option : lumière allumée tant que la salle n'est pas vide.",
 "Arduino Uno, 2 capteurs infrarouges, écran LCD 16×2 I2C, module relais (option).", 2),
("Ouvrir une porte automatiquement quand quelqu'un s'approche.",
 "Le HC-SR04 mesure la distance devant la porte. Si une personne est détectée, le servomoteur ouvre la porte puis la referme après quelques secondes sans détection.",
 "Arduino Uno, capteur à ultrasons HC-SR04, servomoteur SG90, maquette de porte.", 1),
("Réaliser une calculatrice simple (+, −, ×, ÷).",
 "Le clavier 4×4 sert à saisir les nombres ; les touches A, B, C, D choisissent l'opération, « # » donne le résultat et « * » efface. L'Arduino calcule et affiche sur le LCD.",
 "Arduino Uno, clavier matriciel 4×4, écran LCD 16×2 I2C.", 2),
("Jeu de mémoire du type « Simon ».",
 "L'Arduino allume une séquence aléatoire de LED avec des sons. Le joueur la reproduit avec les boutons ; à chaque réussite la séquence s'allonge, à la première erreur le jeu recommence.",
 "Arduino Uno, 4 LED de couleurs + résistances, 4 boutons-poussoirs, buzzer.", 2),
("Montrer le fonctionnement des portes logiques de base.",
 "Deux boutons représentent les entrées A et B. Un troisième bouton choisit la porte (ET, OU, NON, NON-ET, NON-OU, OU exclusif) ; l'Arduino calcule la sortie et l'affiche sur une LED (et le nom de la porte sur un LCD).",
 "Arduino Uno, 3 boutons-poussoirs, LED + résistances, écran LCD (option).", 1),
("Commander un feu de circulation avec un compte à rebours.",
 "L'Arduino allume successivement vert, orange et rouge avec des durées fixées. L'afficheur 7 segments (module TM1637) montre le temps restant. Option : bouton piéton.",
 "Arduino Uno, 3 LED (vert, orange, rouge) + résistances, afficheur 7 segments 4 chiffres TM1637, bouton (option).", 1),
("Faire couler l'eau quand on approche les mains, sans toucher le robinet.",
 "Un capteur (ultrasons ou IR) détecte les mains sous le robinet. L'Arduino active le relais de la pompe (ou d'une électrovanne) et l'arrête dès que les mains sont retirées.",
 "Arduino Uno, capteur HC-SR04 ou IR, module relais, mini-pompe 5 V (ou électrovanne), alimentation externe, réservoir.", 1),
("Mesurer la température et l'afficher en degrés Celsius.",
 "Le LM35 donne 10 mV par °C. L'Arduino lit la tension sur une entrée analogique et calcule T = tension × 100, puis l'affiche sur le LCD.",
 "Arduino Uno, capteur LM35, écran LCD 16×2 I2C.", 1),
("Aider à reculer en signalant la distance d'un obstacle.",
 "Le HC-SR04 mesure la distance. Plus l'obstacle est proche, plus le buzzer bipe vite ; les LED verte, jaune et rouge indiquent la zone. Le LCD affiche la distance en cm.",
 "Arduino Uno, capteur HC-SR04, buzzer, 3 LED + résistances, écran LCD 16×2 (option).", 1),
("Arroser une plante automatiquement quand la terre est sèche.",
 "La sonde mesure l'humidité du sol. En dessous d'un seuil, l'Arduino active le relais de la pompe jusqu'à ce que le sol soit assez humide. Le LCD affiche l'humidité et l'état de la pompe.",
 "Arduino Uno, capteur d'humidité du sol, module relais, mini-pompe à eau, alimentation externe, écran LCD 16×2.", 1),
("Détecter une présence dans une pièce et déclencher une alarme.",
 "Le capteur PIR HC-SR501 détecte le rayonnement infrarouge d'une personne en mouvement et passe sa sortie à l'état haut. L'Arduino déclenche alors le buzzer et la LED. Option : bouton pour armer ou désarmer.",
 "Arduino Uno, capteur PIR HC-SR501, buzzer, LED + résistance.", 1),
("Distribuer un objet (bonbon, pièce…) à la demande.",
 "Quand on appuie sur le bouton ou qu'une main est détectée par le capteur IR, le servomoteur ouvre brièvement la trappe : un objet tombe, puis la trappe se referme.",
 "Arduino Uno, servomoteur SG90, capteur infrarouge, bouton-poussoir, alimentation externe 5 V, maquette en carton.", 1),
("Mettre en marche un ventilateur quand il fait trop chaud.",
 "Le DHT11 mesure la température. Au-dessus d'un seuil (par exemple 30 °C), l'Arduino active le relais qui alimente le ventilateur ; le LCD affiche la température et l'état du ventilateur.",
 "Arduino Uno, capteur DHT11, module relais 5 V, ventilateur DC 12 V, alimentation 12 V, écran LCD 16×2.", 1),
("Commander une LED et une lampe depuis son smartphone.",
 "Une application Bluetooth du téléphone envoie des caractères au module HC-05 ; l'Arduino les lit sur la liaison série et allume ou éteint la LED et le relais de la lampe. La broche RX du HC-05 est en 3,3 V : prévoir un pont diviseur.",
 "Arduino Uno, module Bluetooth HC-05, module relais, lampe, LED + 220 Ω, résistances du pont diviseur, smartphone.", 2),
("Régler la vitesse d'un moteur avec un potentiomètre.",
 "L'Arduino lit le potentiomètre (0 à 1023), le convertit en 0 à 255 avec map(), puis envoie un signal PWM sur la grille du MOSFET qui commande le moteur. La diode de roue libre protège le MOSFET.",
 "Arduino Uno, potentiomètre 10 kΩ, MOSFET IRLZ44N (ou transistor), diode 1N4007, moteur DC, alimentation externe 6-12 V.", 2),
("Orienter un panneau vers la source de lumière.",
 "Deux LDR, chacune en pont diviseur, sont placées de part et d'autre du panneau. L'Arduino compare les deux tensions et fait tourner le servomoteur vers le côté le plus éclairé jusqu'à l'équilibre.",
 "Arduino Uno, 2 photorésistances, 2 résistances 10 kΩ, servomoteur SG90, maquette de panneau, lampe.", 2),
("Détecter une flamme et donner l'alerte.",
 "Le capteur de flamme est sensible à l'infrarouge émis par le feu ; sa sortie change d'état quand une flamme est proche (seuil réglable par potentiomètre). L'Arduino déclenche le buzzer et la LED.",
 "Arduino Uno, capteur de flamme, buzzer, LED + résistance, relais + pompe (option).", 1),
]
